fix timeout issue

diff --git a/tests/nvme/070 b/tests/nvme/070
--- a/tests/nvme/070
+++ b/tests/nvme/070
@@ -6,6 +6,8 @@
 
 . tests/nvme/rc
 
+TIMEOUT=10
+
 DESCRIPTION="test nvme-fc marginal path handling"
 
 requires() {
@@ -57,21 +59,21 @@ _rport_set_online() {
 	_setup_nvmet_port_marginal "$(_subsys_get_port "$RPORT")" "live"
 }
 
-_rport_is_online() {
+_rport_is_online_raw() {
 	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
 
 	[[ "$(cat "$RPORT"/state)" == "live" ]]
 	# Returns Success or Fail
 }
 
-_rport_is_marginal() {
+_rport_is_marginal_raw() {
 	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
 
 	[[ "$(cat "$RPORT"/state)" == "marginal" ]]
 	# Returns Success or Fail
 }
 
-_rport_in_use() {
+_rport_in_use_raw() {
 	local SUBSYS_PATH=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
 
 	# there should only be one "nvme3c9n1" afaik
@@ -79,12 +81,60 @@ _rport_in_use() {
 	# Returns exit code 0 if in use, 1 if not in use
 }
 
-_rport_optimized() {
+_rport_is_optimized() {
 	local SUBSYS_PATH=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
 
 	# there should only be one "nvme3c9n1" afaik
 	[[ "$(cat "$SUBSYS_PATH"/nvme*/ana_state)" == "optimized" ]]
 	# Returns exit code 0 if optimized, 1 if not optimized
+}
+
+_rport_is_online() {
+	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
+	local -i time_passed=0
+
+	for (( time_passed=0; time_passed < TIMEOUT; time_passed++ )); do
+		_rport_is_online_raw "$RPORT" && return 0 || true
+		sleep 1
+	done
+	return 1
+	# Returns Success or Fail
+}
+
+_rport_is_marginal() {
+	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
+	local -i time_passed=0
+
+	for (( time_passed=0; time_passed < TIMEOUT; time_passed++ )); do
+		_rport_is_marginal_raw "$RPORT" && return 0 || true
+		sleep 1
+	done
+	return 1
+	# Returns Success or Fail
+}
+
+_rport_in_use() {
+	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
+	local -i time_passed=0
+
+	for (( time_passed=0; time_passed < TIMEOUT; time_passed++ )); do
+		_rport_in_use_raw "$RPORT" && return 0 || true
+		sleep 1
+	done
+	return 1
+	# Returns exit code 0 if in use, 1 if not in use
+}
+
+_rport_not_in_use() {
+	local RPORT=$1 # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
+	local -i time_passed=0
+
+	for (( time_passed=0; time_passed < TIMEOUT; time_passed++ )); do
+		_rport_in_use_raw "$RPORT" || return 0
+		sleep 1
+	done
+	return 1
+	# Returns exit code 0 if in not use, 1 if in use
 }
 
 # check if link is marginal or not
@@ -112,7 +162,7 @@ _rport_check_use() {
 	local STATE=$2 # "Online"
 
 	if [[ "$STATE" == "Online" ]]; then
-		if ! _rport_in_use "$RPORT" ; then
+		if _rport_not_in_use "$RPORT" ; then
 			echo FC port on \("$RPORT"\) is not being used, expected use.
 			return 1
 		fi
@@ -132,7 +182,7 @@ _rport_check_opt() {
 
 	_rport_check_online "$RPORT" "$STATE"
 	# Only optimized paths will be in use
-	if _rport_optimized "$RPORT"; then
+	if _rport_is_optimized "$RPORT"; then
 		_rport_check_use "$RPORT" "$STATE"
 	else
 		_rport_check_use "$RPORT" Marginal
@@ -150,21 +200,43 @@ _rport_check() {
 	# Returns Success or Fail
 }
 
-# Check if one of the marginal paths is in use
-_rport_check_one_use_online() {
-	local -a RPORTS_PATHS=("$@") #  /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
+_rport_num_in_use() {
+	local -a RPORTS_PATHS=("$@") # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
+	local -i num_in_use=0
 
-	# Check if one of the online paths is in use
+	# Check if one of the marginal paths is in use
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		# If path is Marginal, continue to the next path
-		_rport_check_online "$subsys_path" Online || continue
-		# One of the online paths should be in use
-		# "!" inverts the return code, so returns false if path is in use,
-		# running the return statement
-		! _rport_in_use "$subsys_path" || return 0
+		_rport_in_use "$subsys_path" || continue
+		num_in_use=$((num_in_use + 1))
 	done
 
-	echo No FC ports are being used, expected atleast one in use when all are online in numa mode.
+	echo "$num_in_use"
+	# Returns number of links in use
+}
+
+# Check if one of the paths is in use
+_rport_check_one_use() {
+	local STATE=$1
+	shift
+	local -a RPORTS_PATHS=("$@") #  /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
+	local -i time_passed=0
+	local -i count_in_use=0
+
+	for (( time_passed=0; time_passed < TIMEOUT; time_passed++ )); do
+		# Check if one of the online paths is in use
+		count_in_use=$(_rport_num_in_use "${RPORTS_PATHS[@]}")
+		if [ $count_in_use -eq 1 ]; then
+			return 0
+		fi
+		sleep 1
+	done
+
+	if [ $count_in_use -gt 1 ]; then
+		echo More than one FC port is being used, expected only one in use when all are "$STATE" in numa mode.
+		return 1
+	fi
+
+	echo No FC ports are being used, expected atleast one in use when all are "$STATE" in numa mode.
 	# None of the online paths were in use
 	return 1
 
@@ -182,7 +254,7 @@ test_set_all_online() {
 	done
 
 	if [ "$IOPOLICY" == "numa" ]; then
-		_rport_check_one_use_online "${RPORTS_PATHS[@]}" || return 1
+		_rport_check_one_use "online" "${RPORTS_PATHS[@]}" || return 1
 	else
 		for subsys_path in "${RPORTS_PATHS[@]}"; do
 			# Only optimized paths will be in use
@@ -217,35 +289,22 @@ test_set_one_host_marginal() {
 	done
 }
 
-
-# Check if one of the marginal paths is in use
-_rport_check_one_use_marginal() {
-	local -a RPORTS_PATHS=("$@") # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
-
-	# Check if one of the marginal paths is in use
-	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		_rport_check_online "$subsys_path" Marginal
-		# One of the marginal paths should be in use
-		# "!" inverts the return code, so returns false if path is in use,
-		# running the return statement
-		! _rport_in_use "$subsys_path" || return 0
-	done
-
-	echo No FC ports are being used, expected one in use when all are marginal.
-	# None of the marginal paths were in use
-	return 1
-
-	# Returns Success or Fail
-}
-
 test_set_all_marginal() {
 	local -a RPORTS_PATHS=("$@") # /sys/devices/virtual/nvme-subsystem/nvme-subsys3/nvme9
 
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
 		_rport_set_marginal "$subsys_path" || return 1
+		_rport_check_online "$subsys_path" Marginal || return 1
 	done
 
-	_rport_check_one_use_marginal "${RPORTS_PATHS[@]}"
+	if [ "$IOPOLICY" == "numa" ]; then
+		_rport_check_one_use "marginal" "${RPORTS_PATHS[@]}" || return 1
+	else
+		for subsys_path in "${RPORTS_PATHS[@]}"; do
+			# Only optimized paths will be in use
+			_rport_check_opt "$subsys_path" Marginal || return 1
+		done
+	fi
 }
 
 test_set_one_non_optimized_online() {
@@ -255,7 +314,7 @@ test_set_one_non_optimized_online() {
 	# First set one non-optimized online to online then check optimized paths
 	local next_marginal=0
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		if ! _rport_optimized "$subsys_path"; then
+		if ! _rport_is_optimized "$subsys_path"; then
 			if [ $next_marginal == 1 ]; then
 				_rport_check "$subsys_path" Marginal || return 1
 				break
@@ -267,7 +326,7 @@ test_set_one_non_optimized_online() {
 	done
 	# Check optimized paths
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		if _rport_optimized "$subsys_path"; then
+		if _rport_is_optimized "$subsys_path"; then
 			# Optimized paths will not be in use
 			_rport_check_opt "$subsys_path" Marginal || return 1
 		fi
@@ -282,7 +341,7 @@ test_set_all_non_optimized_online() {
 	# Set all non-optimized online
 	local numa_in_use=0
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		if _rport_optimized "$subsys_path"; then
+		if _rport_is_optimized "$subsys_path"; then
 			_rport_check "$subsys_path" Marginal || return 1
 		else
 			_rport_set_online "$subsys_path" || return 1
@@ -306,7 +365,7 @@ set_one_optimized_online() {
 	# Set one optimized online
 	local next_marginal=0
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		if _rport_optimized "$subsys_path"; then
+		if _rport_is_optimized "$subsys_path"; then
 			if [ $next_marginal == 1 ]; then
 				_rport_check "$subsys_path" Marginal || return 1
 				break
@@ -327,7 +386,7 @@ test_set_all_non_one_optimized_online() {
 
 	# Check non-optimized paths
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		if ! _rport_optimized "$subsys_path"; then
+		if ! _rport_is_optimized "$subsys_path"; then
 			# Only optimized paths will be in use
 			_rport_check_opt "$subsys_path" Online || return 1
 		fi
@@ -343,7 +402,7 @@ test_set_one_optimized_online() {
 
 	# Check non-optimized paths
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		if ! _rport_optimized "$subsys_path"; then
+		if ! _rport_is_optimized "$subsys_path"; then
 			# Only optimized paths will be in use
 			_rport_check_opt "$subsys_path" Marginal || return 1
 		fi
@@ -358,7 +417,7 @@ test_set_two_optimized_online() {
 	# Set two optimized online
 	local numa_in_use=0
 	for subsys_path in "${RPORTS_PATHS[@]}"; do
-		if _rport_optimized "$subsys_path"; then
+		if _rport_is_optimized "$subsys_path"; then
 			_rport_set_online "$subsys_path" || return 1
 			if [ "$IOPOLICY" == "numa" ] && [ $numa_in_use == 0 ]; then
 				_rport_check "$subsys_path" Online || return 1
